#define I2C_SDA_PIN 23
#define I2C_SCL_PIN 19

#define ACCEL1_ADDR 0x18
#define GYRO1_ADDR 0x68
#define ACCEL2_ADDR 0x19
#define GYRO2_ADDR 0x69

#define ABERRANT_DATA 100.0f

#define SAMPLING_RATE 50.0f // in Hz
#define CUTOFF_FREQ 5.0f // in Hz

//#define DEBUG
//#define SERIAL_STREAM

enum CORE0_FSM {
    CORE0_ORIENT_ACQ,
    CORE0_ACCEL_ACQ,
    CORE0_IDLE,
    CORE0_SETUP_INTERRUPT
};

enum CORE1_FSM {
    CORE1_IDLE,
    CORE1_CMD_PROCESSING,
    CORE1_ORIENT_STREAM,
    CORE1_ACCEL_STREAM
};